// ============================================================================
//   Netra Install Fix Script  (scope-agnostic)
//
//   How it works:
//     1. Looks up the scoped application by NAME ("netra"). Whatever the
//        company id is (x_NNNNN_netra), this script finds the scope.
//     2. Substitutes the placeholder __NETRA_SCOPE__ in every embedded source
//        string with the detected scope, then provisions every artifact:
//          - 5 tables (notification, user_pref, context, watchlist, kb_embedding)
//          - 9 Script Includes
//          - 1 Business Rule on sys_journal_field
//          - 1 Scheduled Job ("Netra Watch", every 3 minutes)
//          - 1 Scripted REST API + 3 resources (command, notifications, ping)
//          - 1 Service Portal Widget (netra-mic)
//          - 4 scoped system properties (gemini_api_key, gemini_model,
//            sentiment_llm, notify_author)
//          - Cross-scope privileges for every OOB table Netra touches
//
//   Idempotent — re-running updates records in place.
//   The script is auto-generated by netra-snow/scripts/build-fix-script.ps1.
// ============================================================================

(function () {
    'use strict';

    // The scoped app to install Netra into. Resolution order:
    //   1. Hardcoded sys_id (set this if you know it — most reliable).
    //   2. Any of APP_NAME_CANDIDATES by sys_app.name (case-insensitive).
    //   3. Any sys_app whose scope ends with one of SCOPE_SUFFIXES.
    var APP_SYS_ID_HINT     = 'cbb86f0f93b0cf10936af0a75d03d662';
    var APP_NAME_CANDIDATES = ['Netra_V1', 'netra_v1', 'Netra', 'netra'];
    var SCOPE_SUFFIXES      = ['_netra_v1', '_netra'];

    var log = [];
    function say(msg) {
        log.push(msg);
        // gs.print is fenced in scoped apps; gs.info works cross-scope
        if (typeof gs.print === 'function') {
            try { gs.print(msg); return; } catch (e) {}
        }
        gs.info(msg);
    }

    /* =========================================================
     *  EMBEDDED SOURCE  (populated by the generator)
     * ========================================================= */

    /*__EMBEDDED_SOURCE__*/

    /* =========================================================
     *  Resolve the scope
     * ========================================================= */
    function resolveScope() {
        var gr;

        // Strategy 1 — known sys_id
        if (APP_SYS_ID_HINT) {
            gr = new GlideRecord('sys_app');
            if (gr.get(APP_SYS_ID_HINT)) {
                say('  resolved app by sys_id hint');
                return { sys_id: String(gr.sys_id), scope: String(gr.scope), name: String(gr.name) };
            }
        }

        // Strategy 2 — name match (case-insensitive against any candidate)
        for (var i = 0; i < APP_NAME_CANDIDATES.length; i++) {
            gr = new GlideRecord('sys_app');
            gr.addQuery('name', APP_NAME_CANDIDATES[i]);
            gr.orderByDesc('sys_updated_on');
            gr.setLimit(1);
            gr.query();
            if (gr.next()) {
                say('  resolved app by name: ' + APP_NAME_CANDIDATES[i]);
                return { sys_id: String(gr.sys_id), scope: String(gr.scope), name: String(gr.name) };
            }
        }

        // Strategy 3 — scope ends with one of the suffixes
        for (var j = 0; j < SCOPE_SUFFIXES.length; j++) {
            gr = new GlideRecord('sys_app');
            gr.addEncodedQuery('scopeLIKE' + SCOPE_SUFFIXES[j]);
            gr.orderByDesc('sys_updated_on');
            gr.setLimit(1);
            gr.query();
            if (gr.next()) {
                say('  resolved app by scope suffix: ' + SCOPE_SUFFIXES[j]);
                return { sys_id: String(gr.sys_id), scope: String(gr.scope), name: String(gr.name) };
            }
        }

        return null;
    }

    /* =========================================================
     *  String substitution
     * ========================================================= */
    function fillScope(srcText, scope) {
        if (!srcText) return srcText;
        return String(srcText).replace(/__NETRA_SCOPE__/g, scope);
    }

    /* =========================================================
     *  Provisioning helpers
     * ========================================================= */

    function upsertTable(name, label, scopeSysId, columns) {
        var gr = new GlideRecord('sys_db_object');
        gr.addQuery('name', name);
        gr.setLimit(1);
        gr.query();
        if (!gr.next()) {
            gr.initialize();
            gr.name = name;
            gr.label = label;
            gr.sys_scope = scopeSysId;
            gr.super_class = '';
            gr.is_extendable = false;
            gr.access = 'public';
            gr.create_access_controls = true;
            gr.insert();
            say('  + table ' + name);
        } else {
            say('  = table ' + name + ' (exists)');
        }
        columns.forEach(function (col) { upsertColumn(name, col, scopeSysId); });
    }

    function upsertColumn(tableName, col, scopeSysId) {
        var d = new GlideRecord('sys_dictionary');
        d.addQuery('name', tableName);
        d.addQuery('element', col.name);
        d.setLimit(1);
        d.query();
        if (!d.next()) {
            d.initialize();
            d.name = tableName;
            d.element = col.name;
            d.sys_scope = scopeSysId;
        }
        d.column_label = col.label || col.name;
        d.internal_type = col.type;
        d.max_length = col.length || (col.type === 'boolean' ? 40 : 40);
        if (col.type === 'reference' && col.ref) d.reference = col.ref;
        if (col.default != null) d.default_value = String(col.default);
        d.mandatory = !!col.mandatory;
        d.active = true;
        if (d.isValidRecord() && d.sys_id) d.update();
        else d.insert();
    }

    function upsertScriptInclude(name, scopeSysId, scope, description, source) {
        var gr = new GlideRecord('sys_script_include');
        gr.addQuery('name', name);
        gr.addQuery('sys_scope', scopeSysId);
        gr.setLimit(1);
        gr.query();
        if (!gr.next()) {
            gr.initialize();
            gr.name = name;
            gr.api_name = scope + '.' + name;
            gr.sys_scope = scopeSysId;
            gr.access = 'package_private';
            gr.client_callable = false;
            gr.active = true;
        }
        gr.description = description;
        gr.script = fillScope(source, scope);
        if (gr.sys_id && gr.isValidRecord()) gr.update();
        else gr.insert();
        say('  > script include ' + name);
    }

    function upsertBusinessRule(name, scopeSysId, scope, description, table, when, opts, source) {
        var gr = new GlideRecord('sys_script');
        gr.addQuery('name', name);
        gr.addQuery('sys_scope', scopeSysId);
        gr.setLimit(1);
        gr.query();
        if (!gr.next()) {
            gr.initialize();
            gr.name = name;
            gr.sys_scope = scopeSysId;
            gr.access = 'package_private';
        }
        gr.description = description;
        gr.collection = table;
        gr.when = when;
        gr.action_insert = !!opts.onInsert;
        gr.action_update = !!opts.onUpdate;
        gr.action_delete = !!opts.onDelete;
        gr.advanced = true;
        gr.active = true;
        gr.order = 100;
        gr.script = fillScope(source, scope);
        if (gr.sys_id && gr.isValidRecord()) gr.update();
        else gr.insert();
        say('  > business rule ' + name + ' on ' + table);
    }

    function upsertScheduledJob(name, scopeSysId, scope, source, periodHHMMSS) {
        var gr = new GlideRecord('sysauto_script');
        gr.addQuery('name', name);
        gr.addQuery('sys_scope', scopeSysId);
        gr.setLimit(1);
        gr.query();
        if (!gr.next()) {
            gr.initialize();
            gr.name = name;
            gr.sys_scope = scopeSysId;
        }
        gr.active = true;
        gr.run_type = 'periodically';
        gr.run_period = '1970-01-01 ' + periodHHMMSS;
        gr.run_start = new GlideDateTime();
        gr.script = fillScope(source, scope);
        if (gr.sys_id && gr.isValidRecord()) gr.update();
        else gr.insert();
        say('  > scheduled job ' + name + ' (every ' + periodHHMMSS + ')');
    }

    function upsertScriptedRestService(name, apiId, scopeSysId) {
        var gr = new GlideRecord('sys_ws_definition');
        gr.addQuery('service_id', apiId);
        gr.addQuery('sys_scope', scopeSysId);
        gr.setLimit(1);
        gr.query();
        if (!gr.next()) {
            gr.initialize();
            gr.name = name;
            gr.service_id = apiId;
            gr.sys_scope = scopeSysId;
        }
        gr.short_description = 'Voice command endpoints for Netra.';
        if (gr.sys_id && gr.isValidRecord()) gr.update();
        else gr.insert();
        return String(gr.sys_id);
    }

    function upsertScriptedRestOp(serviceSysId, name, method, path, scopeSysId, scope, source) {
        var gr = new GlideRecord('sys_ws_operation');
        gr.addQuery('name', name);
        gr.addQuery('web_service_definition', serviceSysId);
        gr.setLimit(1);
        gr.query();
        if (!gr.next()) {
            gr.initialize();
            gr.name = name;
            gr.web_service_definition = serviceSysId;
            gr.sys_scope = scopeSysId;
        }
        gr.http_method = method;
        gr.relative_path = path;
        gr.requires_authentication = true;
        gr.requires_acl_authorization = false;
        gr.active = true;
        gr.produces = 'application/json';
        gr.consumes = 'application/json';
        gr.operation_script = fillScope(source, scope);
        if (gr.sys_id && gr.isValidRecord()) gr.update();
        else gr.insert();
        say('  > REST resource ' + method + ' ' + path);
    }

    function upsertWidget(id, name, scopeSysId, scope, template, clientScript, serverScript, css, optionSchema) {
        var gr = new GlideRecord('sp_widget');
        gr.addQuery('id', id);
        gr.setLimit(1);
        gr.query();
        if (!gr.next()) {
            gr.initialize();
            gr.id = id;
            gr.sys_scope = scopeSysId;
        }
        gr.name = name;
        gr.template = fillScope(template, scope);
        gr.client_script = fillScope(clientScript, scope);
        gr.script = fillScope(serverScript, scope);
        gr.css = fillScope(css, scope);
        gr.option_schema = optionSchema || '[]';
        gr.public = false;
        gr.has_preview = false;
        if (gr.sys_id && gr.isValidRecord()) gr.update();
        else gr.insert();
        say('  > widget ' + id);
    }

    /* =========================================================
     *  MAIN
     * ========================================================= */

    say('=== Netra install starting ===');

    var info = resolveScope();
    if (!info) {
        say('');
        say('ERROR: could not find the Netra scoped application.');
        say('Tried:');
        say('  - sys_id ' + APP_SYS_ID_HINT);
        say('  - names ' + APP_NAME_CANDIDATES.join(', '));
        say('  - scope suffixes ' + SCOPE_SUFFIXES.join(', '));
        say('Create a scoped app named "Netra_V1" (or similar) first, then re-run.');
        return;
    }
    var scope = info.scope;
    var scopeSysId = info.sys_id;
    say('App:   ' + info.name);
    say('Scope: ' + scope);
    say('AppID: ' + scopeSysId);

    /* ---- Tables ---- */
    say('');
    say('Tables...');
    upsertTable(scope + '_notification', 'Netra Notification', scopeSysId, [
        { name: 'user',          type: 'reference', ref: 'sys_user', label: 'User' },
        { name: 'ticket_sys_id', type: 'string',    length: 32,   label: 'Ticket sys_id' },
        { name: 'ticket_number', type: 'string',    length: 32,   label: 'Ticket Number' },
        { name: 'kind',          type: 'string',    length: 40,   label: 'Kind' },
        { name: 'message',       type: 'string',    length: 1000, label: 'Message' },
        { name: 'delivered',     type: 'boolean',                 label: 'Delivered', default: 'false' },
        { name: 'delivered_at',  type: 'glide_date_time',         label: 'Delivered At' }
    ]);
    upsertTable(scope + '_user_pref', 'Netra User Pref', scopeSysId, [
        { name: 'user',              type: 'reference', ref: 'sys_user', label: 'User' },
        { name: 'active',            type: 'boolean',                 label: 'Active', default: 'true' },
        { name: 'paused_until',      type: 'glide_date_time',         label: 'Paused Until' },
        { name: 'last_scan_time',    type: 'glide_date_time',         label: 'Last Scan' },
        { name: 'watch_assignments', type: 'boolean',                 label: 'Watch Assignments', default: 'true' },
        { name: 'watch_comments',    type: 'boolean',                 label: 'Watch Comments',    default: 'true' },
        { name: 'watch_approvals',   type: 'boolean',                 label: 'Watch Approvals',   default: 'true' },
        { name: 'voice_mode',        type: 'string', length: 20,      label: 'Voice Mode',        default: 'normal' }
    ]);
    upsertTable(scope + '_context', 'Netra Context', scopeSysId, [
        { name: 'user',           type: 'reference', ref: 'sys_user', label: 'User' },
        { name: 'focus_table',    type: 'string', length: 40,        label: 'Focus Table' },
        { name: 'focus_sys_id',   type: 'string', length: 32,        label: 'Focus sys_id' },
        { name: 'focus_number',   type: 'string', length: 32,        label: 'Focus Number' },
        { name: 'focus_set_at',   type: 'glide_date_time',           label: 'Focus Set At' },
        // R4.7 - last_utterance holds the unified 'CTX:' JSON blob (draft, mem,
        // vocab, aliases, sentiment). Sized to match MEM_CAP=100 turns.
        { name: 'last_utterance', type: 'string', length: 250000,    label: 'Last Utterance' }
    ]);
    upsertTable(scope + '_watchlist', 'Netra Watchlist', scopeSysId, [
        { name: 'user',          type: 'reference', ref: 'sys_user', label: 'User' },
        { name: 'record_table',  type: 'string', length: 40,        label: 'Record Table' },
        { name: 'record_sys_id', type: 'string', length: 32,        label: 'Record sys_id' },
        { name: 'record_number', type: 'string', length: 32,        label: 'Record Number' }
    ]);
    // R4.7 - RAG embedding cache for semantic KB search (gemini-embedding-001)
    upsertTable(scope + '_kb_embedding', 'Netra KB Embedding', scopeSysId, [
        { name: 'source_table',  type: 'string', length: 40,    label: 'Source Table' },
        { name: 'source_sys_id', type: 'string', length: 32,    label: 'Source sys_id' },
        { name: 'source_number', type: 'string', length: 32,    label: 'Source Number' },
        { name: 'title',         type: 'string', length: 240,   label: 'Title' },
        { name: 'body_digest',   type: 'string', length: 1500,  label: 'Body Digest' },
        { name: 'embedding',     type: 'string', length: 32000, label: 'Embedding (JSON 768 floats)' },
        { name: 'model',         type: 'string', length: 64,    label: 'Embedding Model' },
        { name: 'embedded_at',   type: 'glide_date_time',       label: 'Embedded At' }
    ]);

    /* ---- Script Includes ---- */
    say('');
    say('Script Includes...');
    upsertScriptInclude('NetraIntent',     scopeSysId, scope, 'Regex intent parser with smalltalk, multi-turn, advanced commands.', SRC.NetraIntent);
    upsertScriptInclude('NetraTools',      scopeSysId, scope, 'GlideRecord ops: incidents, approvals, watchlist, prefs.',           SRC.NetraTools);
    upsertScriptInclude('NetraResponder',  scopeSysId, scope, 'Composes spoken replies; routes every intent.',                     SRC.NetraResponder);
    upsertScriptInclude('NetraScanner',    scopeSysId, scope, 'Periodic scanner for assignments, approvals, tasks.',                SRC.NetraScanner);
    upsertScriptInclude('NetraKnowledge',  scopeSysId, scope, 'Keyword-scored search over kb_knowledge.',                          SRC.NetraKnowledge);
    upsertScriptInclude('NetraChat',       scopeSysId, scope, 'Read and reply to Connect Chat conversations.',                     SRC.NetraChat);
    upsertScriptInclude('NetraSummarizer', scopeSysId, scope, 'Extractive summary of long text (no LLM).',                         SRC.NetraSummarizer);
    upsertScriptInclude('NetraContext',    scopeSysId, scope, 'Per-user conversational context (last ticket etc.).',               SRC.NetraContext);
    upsertScriptInclude('NetraNavigator',  scopeSysId, scope, 'Resolves spoken destinations to portal URLs.',                      SRC.NetraNavigator);

    /* ---- Business Rule ---- */
    say('');
    say('Business Rule...');
    upsertBusinessRule(
        'Netra Notify On Comment', scopeSysId, scope,
        'Async after-insert on sys_journal_field; enqueues a notification.',
        'sys_journal_field', 'async', { onInsert: true },
        SRC.netra_notify_on_comment
    );

    /* ---- Scheduled Job ---- */
    say('');
    say('Scheduled Job...');
    upsertScheduledJob('Netra Watch', scopeSysId, scope, SRC.netra_watch, '00:03:00');

    /* ---- Scripted REST API ---- */
    say('');
    say('Scripted REST API...');
    var svc = upsertScriptedRestService('Netra Voice', 'voice', scopeSysId);
    upsertScriptedRestOp(svc, 'command',       'POST', '/command',       scopeSysId, scope, SRC.command);
    upsertScriptedRestOp(svc, 'notifications', 'GET',  '/notifications', scopeSysId, scope, SRC.notifications);
    upsertScriptedRestOp(svc, 'ping',          'GET',  '/ping',          scopeSysId, scope, SRC.ping);
    say('  Base path: /api/' + scope + '/voice');

    /* ---- System properties ---- */
    say('');
    say('System properties...');
    function upsertProp(suffix, value, desc) {
        var p = new GlideRecord('sys_properties');
        p.addQuery('name', scope + '.' + suffix);
        p.setLimit(1); p.query();
        if (!p.next()) {
            p.initialize();
            p.setValue('name', scope + '.' + suffix);
            p.setValue('sys_scope', scopeSysId);
            p.setValue('type', 'string');
        }
        // never clobber an existing non-empty api key
        if (suffix === 'gemini_api_key' && String(p.value || '')) { say('  = prop ' + suffix + ' (kept)'); return; }
        p.setValue('value', value);
        p.setValue('description', desc);
        if (p.sys_id && p.isValidRecord()) p.update(); else p.insert();
        say('  > prop ' + scope + '.' + suffix);
    }
    upsertProp('gemini_api_key', '', 'Google AI Studio API key for Gemini. REQUIRED for the conversational brain and TTS. Get a free key at https://aistudio.google.com/apikey');
    upsertProp('gemini_model', 'gemini-flash-lite-latest', 'Primary Gemini model for chat + reasoning. Default tuned for voice-loop latency (~1s). Set to gemini-2.5-flash for richer reasoning at ~2-4s per call.');
    upsertProp('sentiment_llm', 'false', 'When true, refine keyword-detected frustration with an extra Gemini classification call on the reply path (adds ~1-2s on frustrated turns).');
    upsertProp('notify_author', 'false', 'When true, the comment business rule also notifies the comment author.');

    /* ---- Cross-scope privileges ---- */
    say('');
    say('Cross-scope privileges...');
    var privRules = {
        'sc_req_item': ['read'], 'sc_task': ['read'], 'kb_knowledge': ['read'],
        'sys_user': ['read'], 'sys_user_group': ['read'], 'sys_attachment': ['read'],
        'sys_dictionary': ['read'], 'sys_dictionary_override': ['read'],
        'sys_data_policy_rule': ['read'], 'sys_ui_policy': ['read'], 'sys_ui_policy_action': ['read'],
        'sys_db_object': ['read'], 'sys_app': ['read'], 'sys_script_include': ['read'],
        'sys_script': ['read'], 'sysauto_script': ['read'], 'sys_ws_definition': ['read'],
        'sys_ws_operation': ['read'], 'sp_widget': ['read'],
        'sys_cs_message': ['read'], 'sys_cs_session': ['read'], 'sys_cs_session_member': ['read'],
        'cmdb_ci_appl': ['read'], 'sys_choice': ['read'], 'sc_cat_item': ['read'],
        'incident': ['read', 'write', 'create'],
        'change_request': ['read', 'write', 'create'],
        'problem': ['read', 'write', 'create'],
        'sysapproval_approver': ['read', 'write'],
        'sys_journal_field': ['read', 'write', 'create'],
        'sys_sidebar_discussion': ['read', 'write', 'create'],
        'sys_sidebar_discussion_participant': ['read', 'write', 'create'],
        'sys_sidebar_discussion_message': ['read', 'write', 'create'],
        'live_group': ['read', 'write', 'create'],
        'live_group_profile': ['read', 'write', 'create'],
        'live_message': ['read', 'write', 'create'],
        'sys_properties': ['read', 'write'],
        'sys_user_preference': ['read', 'write', 'create', 'delete']
    };
    var privCreated = 0, privSkipped = 0;
    for (var privTable in privRules) {
        for (var pi = 0; pi < privRules[privTable].length; pi++) {
            var privOp = privRules[privTable][pi];
            var privEx = new GlideRecord('sys_scope_privilege');
            privEx.addQuery('source', scopeSysId);
            privEx.addQuery('target_type', 'sys_db_object');
            privEx.addQuery('target_name', privTable);
            privEx.addQuery('operation', privOp);
            privEx.setLimit(1); privEx.query();
            if (privEx.next()) { privSkipped++; continue; }
            var privGr = new GlideRecord('sys_scope_privilege');
            privGr.initialize();
            privGr.setValue('source', scopeSysId);
            privGr.setValue('target_type', 'sys_db_object');
            privGr.setValue('target_name', privTable);
            privGr.setValue('operation', privOp);
            privGr.setValue('status', 'allowed');
            privGr.setValue('sys_scope', scopeSysId);
            if (privGr.insert()) privCreated++;
        }
    }
    say('  privileges: created=' + privCreated + ' existing=' + privSkipped);

    /* ---- Widget ---- */
    say('');
    say('Service Portal Widget...');
    upsertWidget('netra-mic', 'Netra Mic', scopeSysId, scope,
                 SRC.template, SRC.client, SRC.server, SRC.stylesheet, '[]');

    say('');
    say('=== Netra install complete ===');
    say('');
    say('Last step:');
    say('  Service Portal -> Service Portal Configuration -> Designer');
    say('  Open the home page and drag the "Netra Mic" widget onto it.');
    say('  Save, then open /sp in Chrome or Edge, grant microphone, and say "Netra".');

})();
